% Step1_Predator_Model.m    Version 8.0 1/23/03
%
% OBJECTIVE: Develop the aerodynamic and thrust model for a particular aircraft.
%
% INPUTS: a file of basic vehicle constants, e.g. Basic_Constants_Predator.m
% OUTPUTS: In the Matlab workspace will be defined an array called constant.
% Note: memory is cleared at the start of this script.

disp(' '); disp(' ')
disp(' >>>>>>>>>>>Start here, Step1_Predator_Model <<<<<<<<<<<<<<<')
disp(' ')

clear all; close all; format short g
% Note that this code clears MATLAB memory
%                    and can clear time histories that may have been previously 
%                    generated by SIMULINK.

% Get the matrix of constants that pretain to the Predator.
Basic_Constants_Predator; % Use this script to model the Predator aircraft <<<<<
% BasicConstants_Predator.m is called only once and this call is 
% in the statement above.
% If you change to another aircraft called NewAircraft
% you would be wise to change the names of files
% to something like this
%              Step1_NewAircraft_Model.m and 
%              Basic_Constants_NewAircraft.

disp(aircraft); % Display aircraft identification
Make_Constants  % Creates the array called constant used to define the 
%                 aerodynamics and mass properties of the aircraft.
disp(aircraft); % Display aircraft identification
Check_Constants % Check the constants for believability.
disp(aircraft); % Display aircraft identification
