function data = import_eagle_data(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [VARNAME1,VARNAME2,VARNAME3,VARNAME4,VARNAME5,VARNAME6,VARNAME7,VARNAME8,VARNAME9,VARNAME10,VARNAME11,VARNAME12,VARNAME13,VARNAME14,VARNAME15,VARNAME16,VARNAME17,VARNAME18,VARNAME19,VARNAME20,VARNAME21,VARNAME22,VARNAME23,VARNAME24,VARNAME25,VARNAME26,VARNAME27,VARNAME28,VARNAME29,VARNAME30,VARNAME31,VARNAME32,VARNAME33,VARNAME34,VARNAME35,VARNAME36]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [VARNAME1,VARNAME2,VARNAME3,VARNAME4,VARNAME5,VARNAME6,VARNAME7,VARNAME8,VARNAME9,VARNAME10,VARNAME11,VARNAME12,VARNAME13,VARNAME14,VARNAME15,VARNAME16,VARNAME17,VARNAME18,VARNAME19,VARNAME20,VARNAME21,VARNAME22,VARNAME23,VARNAME24,VARNAME25,VARNAME26,VARNAME27,VARNAME28,VARNAME29,VARNAME30,VARNAME31,VARNAME32,VARNAME33,VARNAME34,VARNAME35,VARNAME36]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [VarName1,VarName2,VarName3,VarName4,VarName5,VarName6,VarName7,VarName8,VarName9,VarName10,VarName11,VarName12,VarName13,VarName14,VarName15,VarName16,VarName17,VarName18,VarName19,VarName20,VarName21,VarName22,VarName23,VarName24,VarName25,VarName26,VarName27,VarName28,VarName29,VarName30,VarName31,VarName32,VarName33,VarName34,VarName35,VarName36]
%   = importfile('altimeter1.FDR',7, 7);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/10/06 21:40:15

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 8;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,35]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end

%% Split data into numeric and cell columns.
rawNumericColumns = raw(:, [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,35]);
rawCellColumns = raw(:, [34,36]);


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),rawNumericColumns); % Find non-numeric cells
rawNumericColumns(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
data.col1 = cell2mat(rawNumericColumns(:, 1));
data.col2 = cell2mat(rawNumericColumns(:, 2));
data.col3 = cell2mat(rawNumericColumns(:, 3));
data.col4 = cell2mat(rawNumericColumns(:, 4));
data.col5 = cell2mat(rawNumericColumns(:, 5));
data.col6 = cell2mat(rawNumericColumns(:, 6));
data.col7 = cell2mat(rawNumericColumns(:, 7));
data.col8 = cell2mat(rawNumericColumns(:, 8));
data.col9 = cell2mat(rawNumericColumns(:, 9));
data.col10 = cell2mat(rawNumericColumns(:, 10));
data.col11 = cell2mat(rawNumericColumns(:, 11));
data.col12 = cell2mat(rawNumericColumns(:, 12));
data.col13 = cell2mat(rawNumericColumns(:, 13));
data.col14 = cell2mat(rawNumericColumns(:, 14));
data.col15 = cell2mat(rawNumericColumns(:, 15));
data.col16 = cell2mat(rawNumericColumns(:, 16));
data.col17 = cell2mat(rawNumericColumns(:, 17));
data.col18 = cell2mat(rawNumericColumns(:, 18));
data.col19 = cell2mat(rawNumericColumns(:, 19));
data.col20 = cell2mat(rawNumericColumns(:, 20));
data.col21 = cell2mat(rawNumericColumns(:, 21));
data.col22 = cell2mat(rawNumericColumns(:, 22));
data.col23 = cell2mat(rawNumericColumns(:, 23));
data.col24 = cell2mat(rawNumericColumns(:, 24));
data.col25 = cell2mat(rawNumericColumns(:, 25));
data.col26 = cell2mat(rawNumericColumns(:, 26));
data.col27 = cell2mat(rawNumericColumns(:, 27));
data.col28 = cell2mat(rawNumericColumns(:, 28));
data.col29 = cell2mat(rawNumericColumns(:, 29));
data.col30 = cell2mat(rawNumericColumns(:, 30));
data.col31 = cell2mat(rawNumericColumns(:, 31));
data.col32 = cell2mat(rawNumericColumns(:, 32));
data.col33 = cell2mat(rawNumericColumns(:, 33));

